api/v1beta1/acrpullbinding_types.go, config/crd/bases/msi-acrpull.microsoft.com_acrpullbindings.yaml, controllers/acrpullbinding_controller.go, pkg/auth/auth.go
Add support to use managed identity resource ID instead of client iD in AcrPullBiding.
This PR fixes #9
=> Support using managed identity resource ID in AcrPullBinding

controllers/acrpullbinding_controller.go, controllers/acrpullbinding_controller_test.go
When the linked service account doesn't exist, we can't delete the AcrPullBinding because we will fail at getting the service account and never reaching the finalizer removal stage
=> should continue removing finalizer when service account is not found

.github/workflows/docker-image.yml
Fix the push to ACR condition in workflow. Seems should have condition on the trigger event. it will be 'push' to master when a PR is merged.
=> Fix GH action push to ACR condition

.github/workflows/go.yml
Add cache to Go build workflow. With the cache when there is no mod changes `go mod download` won't need download anything.
=> Add cache to Go build workflow

config/manager/manager.yaml
Enable HA by default for the controller and increase the memory limit.
=> Enable controller HA by default

.github/workflows/go.yml, Makefile, README.md, config/manager/kustomization.yaml, deploy/latest/crd.yaml, deploy/latest/deploy.yaml
Add a Makefile target to build deploy artifacts. With that the GH action can deploy the latest CRD and deployment for CI testing.
I used MCR latest tag for now and will move to msiacrpullci repo once it's public.
=> Add Makefile target to build deploy artifacts

Dockerfile, README.md, controllers/acrpullbinding_controller.go, controllers/acrpullbinding_controller_test.go, main.go, pkg/authorizer/authorizer.go
Adds support for environment variable default on the controller.
3 default values can be set : 
- ACR_SERVER
- MANAGED_IDENTITY_RESOURCE_ID
- MANAGED_IDENTITY_CLIENT_ID
These environment variables are used if the `ACRPullBinding` crd does not set them.
See README section for details.
=> Adds the possibility to set default values on the controller

azure-pipelines.yml, controllers/acrpullbinding_controller_test.go, pkg/authorizer/token_retriever.go, pkg/authorizer/token_retriever_test.go
- For US government cloud and China cloud the ARM resource should be different so allowing it to be modified through env variable instead of hardcoding it
- Also change the agent pool because it is different now
=> Custom ARM resource for sovereign clouds

controllers/acrpullbinding_controller.go, controllers/acrpullbinding_controller_test.go
Noticed that resource ID is essentially a path - if a double slash is passed in there is no dedupe and it will fail to grab the token from IMDS
=> If ResourceId has a duplicate slash it will fail to pull a Token from IMDS

internal/controller/acrpullbinding_controller.go, internal/controller/acrpullbinding_controller_test.go
It is accepted best-practice to only make one mutating API call per reconciliation loop, especially when changing resources that are under a WATCH and will trigger a further reconciliation, as the moment you keep reconciling an object after mutating it, not only are you working off of a stale cache of what the object looks like, but you're also delaying the next processing loop, which would work off of the correct state.
Here, we exit early if we needed to take corrective action to add a finalizer to an ACR pull binding that did not yet have one. The next reconciliation loop will handle the rest of the logic.
=> controller: short-circuit after updating finalizer

internal/controller/acrpullbinding_controller.go
We were searching through the list of secrets for the correct one to use, but then not updating it.
=> controller: fix bug in filtering

Makefile, api/v1beta2/acrpullbinding_types.go, config/helm/templates/acrpull.microsoft.com_acrpullbindings.yaml, config/helm/templates/controller_role.yaml, internal/controller/acrpullbinding_v1beta2_controller.go, internal/controller/acrpullbinding_v1beta2_controller_test.go, test/e2e_test.go, test/e2e_v1beta2_test.go, test/infrastructure/aks.bicep
In environments where users have not annotated their service accounts with the default client/tenant ID to use, or where they have federated many identities to one service account, it is necessary to specity the client and tenant ID for auth with WI explicitly.
=> api/v1beta2: allow targetting custom identities

api/v1beta2/acrpullbinding_types.go, config/helm/templates/acrpull.microsoft.com_acrpullbindings.yaml
Users should be able to tell at a glance what the pull binding is for and whether or not there were any errors in generating the token.
Before:
```
$ kubectl --kubeconfig test/_output/aks.kubeconfig get acrpullbinding --all-namespaces
NAMESPACE               NAME           AGE
v1beta2-msi-scoped      pull-binding   10d
v1beta2-wi-nondefault   pull-binding   10d
v1beta2-wi-scoped       pull-binding   10d
```
After:
```
$ kubectl --kubeconfig test/_output/aks.kubeconfig get acrpullbinding --all-namespaces
NAMESPACE               NAME           SERVER                     EXPIRATION   ERROR
v1beta2-msi-scoped      pull-binding   3j6vsfxh2xtv4.azurecr.io   12h          
v1beta2-wi-nondefault   pull-binding   3j6vsfxh2xtv4.azurecr.io   11h          
v1beta2-wi-scoped       pull-binding …
```
=> api: add printer columns for v1beta2 API

config/helm/templates/validatingadmissionpolicies.yaml
The legacy naming controller needs to be able to remove old pull credential names from the service account. We can remove this in the next release.
=> vap: allow removing legacy pull tokens

internal/controller/acrpullbinding_controller.go, internal/controller/acrpullbinding_controller_test.go, internal/controller/acrpullbinding_v1beta2_controller.go, test/e2e_test.go, test/infrastructure/aks.bicep
If a pull binding is successfully realized, then new errors occur, we should add the error message while retaining information about the last provisioning and expiry times that remain valid. When the reconciler succeeds, we should then clear the error message.
=> *: clear errors when credential provisioning succeeds

Dockerfile, test/e2e_test.go
Not only do we benefit from owning the sources for the images we use to build this project, but we also run the risk of rate-limiting and outages on other registries impacting our ability to ship if we don't.
=> Dockerfile: use MCR for images

config/helm/templates/deployment.yaml, config/helm/values.yaml, internal/controller/acrpullbinding_controller_test.go, internal/controller/acrpullbinding_v1beta2_controller_test.go, internal/controller/generic_controller.go, test/e2e_test.go, test/values.template.yaml
Determining whether or not to take action during a reconciliation as well as if or after how long to wait before re-queueing are both dependent on `time.Now()`. Previously, it was possible for temporal distance between two calls to `time.Now()` to both direct the reconciliation to do nothing as well as to not re-queue for a future time. Clamping the duration will fix this.
=> internal/controller: clamp requeue duration

.github/workflows/e2e.yaml, README.md, cmd/main.go, config/helm/templates/deployment.yaml, config/helm/templates/namespace.yaml, config/helm/templates/validatingadmissionpolicies.yaml, config/helm/values.yaml, internal/controller/acrpullbinding_controller.go, internal/controller/acrpullbinding_controller_test.go, internal/controller/acrpullbinding_v1beta2_controller.go, internal/controller/acrpullbinding_v1beta2_controller_test.go, internal/controller/generic_controller.go, internal/controller/legacy_token_cleanup_controller.go, internal/controller/legacy_token_cleanup_controller_test.go, test/Makefile, test/e2e_v1beta2_test.go, test/eventually.go, test/pullbinding.template.yaml, test/values.template.yaml
Revert "*: remove legacy token cleanup controller"
This reverts commit f202b1a281c34ae05fee6c3b7efb8db09e330aae.
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---
.github: use ubuntu-latest
Ubuntu 20.04 is EOL, there's no need to explicitly use it.
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---
internal/controller: label legacy secrets instead of cleanup
In order to make the name of the pull secret created by this controller
known a prioi, and to paper over the backwards-incompatibility necessary
to support arbitrary length binding names, we need to keep the previous
legacy names unchanged. When the controller starts, labels will need to
be added to previous secrets so we can filter our informers in the
future.
Signed-off-by: Steve Kuznetsov …
=> *: make secret names more easily assumable

internal/controller/acrpullbinding_controller_test.go, internal/controller/acrpullbinding_v1beta2_controller_test.go, internal/controller/generic_controller.go
If the controller notices that extraneous secrets exist that need to be cleaned up, it first needs to remove references to those secrets from the service account. This only happens once the new secret exists and is referenced, so there should be no discontinuity in pull credentials.
=> *: clean up references to old secrets before removing them

config/helm/templates/leader_election_role.yaml
Cleaning up the configmaps permissions, which were previously used for leader election in Kubernetes before the introduction of the leases API. This helps eliminate excessive permissions, reducing permission drift and ensuring stricter access control.
This is a PR from a branch of the repo itself, not my fork -- as requested by Steve.
=> trim configmaps stuff
